services:
  - type: web
    name: qr-extractor
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn -w 4 -b 0.0.0.0:10000 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: PORT
        value: 10000